consul:
  command: -server -bootstrap -rejoin 
  image: progrium/consul:latest
  hostname: "registry"
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
micro:
  command: --registry_address=registry:8500 --api_handler=rpc api
  image: microhq/micro:latest
  links:
    - consul
    - api
  ports:
    - "8080:8080"
api:
  build: ./api/hotel
  command: --registry_address=registry:8500
  links:
    - consul
    - auth
    - geo
    - profile
    - rate
auth:
  build: ./srv/auth
  command: --registry_address=registry:8500
  links:
    - consul
geo:
  build: ./srv/geo
  command: --registry_address=registry:8500
  links:
    - consul
profile:
  build: ./srv/profile
  command: --registry_address=registry:8500
  links:
    - consul
rate:
  build: ./srv/rate
  command: --registry_address=registry:8500
  links:
    - consul
